### ISSUE TITLE
The issue about the dataset

### ISSUE THREAD

**Issue by Beprominent** [IvoryCandy/super-resolution#16]
Hi, it seems that the URL of the dataset is unavailable, could you please provide a zip file of the dataset separately? Thanks.

**Comment by soapisnotfat** [comment]
I have  noticed the problem for a while. It looks like UCB dns management made a mistake and invalidate the URL. Since it's still in the UCB vacation period and I cannot find some other official links, I cannot update the url right now. However there are some GitHub repo having the replicas of the same dataset, you can search and download them.

**Comment by soapisnotfat** [comment]
https://github.com/BIDS/BSDS500
here is an example repo

**Comment by Beprominent** [comment]
Ok, thanks for your response.
